---
title: "Untitled"
author: "ZH"
date: "2023-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#简单示例
```{r}
library(ggplot2)
library(gggenes)
data(example_genes)
head(example_genes)
example_genes<-example_genes %>% filter(molecule=="Genome1")
#example_genes<-read.delim(pipe("pbpaste"),header = TRUE)
p<-ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3")
p+mytheme
```
# 4F10 多个基因位置图。
```{r}
library(ggplot2)
library(gggenes)
# 读取数据
example_genes<-read.csv("Genome_4F10_gene_position.csv",header = TRUE)
# 画几个区域
reg<-c("Ocd","proVWX","OpuE","speC_speF","PutA")
regi<-reg[1]
example_genes<-example_genes %>% filter(region==regi)
p<-ggplot(example_genes, aes(xmin = start, 
                             xmax = end, 
                             y = Genome, 
                             forward = orientation,
                             fill = gene2,
                             label=gene)) +
  geom_gene_arrow() +
  geom_gene_label() +
  facet_wrap(~ region, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Paired")
p #+mytheme

p2<-ggplot(example_genes, aes(xmin = start, 
                              xmax = end, 
                              y = Genome, 
                              forward = orientation,
                              fill = gene,
                              label=gene)) +
  geom_gene_arrow() +
  geom_gene_label() +
  facet_wrap(~ region, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Paired")
p2
#ggarrange(p,p2,
#          ncol = 2,labels = c("a","b"))

```

```{r}
mytheme<- theme(
    plot.title  = element_text(color = "black", size   = 10, hjust = 0.5),  #主标题样式
    #plot.subtitle = element_text(color = "black", size   = 8,hjust = 0.5),  #副标题样式
    text=element_text(size=10,face="plain"),
    axis.title=element_text(size=8,face="plain",color="black"),   #轴标题样式
    axis.text = element_text(size=8,face="plain",color="black"),  #轴刻度样式
    axis.text.x = element_text(colour = "black",angle = 0),
    legend.title = element_text(size=6,face="plain",color="black"), #图例标题
    legend.text = element_text(size=6,face="plain",color="black"),  #图例样式
    legend.background = element_blank(),                            #图例背景
    legend.position="right",                             #图例位置，指定与否默认右侧，不要:none
    axis.line.y = element_line(color = "black", linetype = "solid",linewidth=0.2), # y轴线特征
    axis.line.x = element_line (color = "black",linetype = "solid",linewidth=0.2), # x轴线特征
    panel.grid.major =element_blank(), panel.grid.minor = element_blank(),# 去除任何网格和背景
    panel.border = element_rect(linetype = "solid", size = 0.2,fill = NA))

```